// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// expWArma
List expWArma(const Rcpp::List& iz_, const Rcpp::List& b_, const arma::mat& gam, const Rcpp::List& h_);
RcppExport SEXP _JM2survClayton_expWArma(SEXP iz_SEXP, SEXP b_SEXP, SEXP gamSEXP, SEXP h_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type iz_(iz_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type b_(b_SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type gam(gamSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type h_(h_SEXP);
    rcpp_result_gen = Rcpp::wrap(expWArma(iz_, b_, gam, h_));
    return rcpp_result_gen;
END_RCPP
}
// gammaUpdate_fixDelta_general
List gammaUpdate_fixDelta_general(const Rcpp::List& b_, const Rcpp::List& z_, const Rcpp::List& w_, const Rcpp::List& pb_, const arma::vec& haz, const Rcpp::List& v_, const Rcpp::List& u_, const Rcpp::List& h_, const int& K, const int& q, const int& qq, const int& nev, const arma::vec& jcount);
RcppExport SEXP _JM2survClayton_gammaUpdate_fixDelta_general(SEXP b_SEXP, SEXP z_SEXP, SEXP w_SEXP, SEXP pb_SEXP, SEXP hazSEXP, SEXP v_SEXP, SEXP u_SEXP, SEXP h_SEXP, SEXP KSEXP, SEXP qSEXP, SEXP qqSEXP, SEXP nevSEXP, SEXP jcountSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type b_(b_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type z_(z_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type w_(w_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pb_(pb_SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type haz(hazSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type v_(v_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type u_(u_SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type h_(h_SEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int& >::type q(qSEXP);
    Rcpp::traits::input_parameter< const int& >::type qq(qqSEXP);
    Rcpp::traits::input_parameter< const int& >::type nev(nevSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type jcount(jcountSEXP);
    rcpp_result_gen = Rcpp::wrap(gammaUpdate_fixDelta_general(b_, z_, w_, pb_, haz, v_, u_, h_, K, q, qq, nev, jcount));
    return rcpp_result_gen;
END_RCPP
}
// min0
double min0(double a, double b);
RcppExport SEXP _JM2survClayton_min0(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(min0(a, b));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihoodPoisson_preX
double loglikelihoodPoisson_preX(const arma::vec& Xbeta, const arma::mat& Z, const arma::vec& u, const arma::vec& y, const arma::mat& Sigma);
RcppExport SEXP _JM2survClayton_loglikelihoodPoisson_preX(SEXP XbetaSEXP, SEXP ZSEXP, SEXP uSEXP, SEXP ySEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Xbeta(XbetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihoodPoisson_preX(Xbeta, Z, u, y, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihoodPoissonCpp_n
double loglikelihoodPoissonCpp_n(const arma::vec& beta, const arma::mat& Sigma, const arma::vec& u, const arma::vec& y, const arma::mat& X, const arma::mat& Z);
RcppExport SEXP _JM2survClayton_loglikelihoodPoissonCpp_n(SEXP betaSEXP, SEXP SigmaSEXP, SEXP uSEXP, SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihoodPoissonCpp_n(beta, Sigma, u, y, X, Z));
    return rcpp_result_gen;
END_RCPP
}
// logAcceptPoisson_n
double logAcceptPoisson_n(const arma::vec& beta, const arma::mat& Sigma, const arma::vec& ucur, const arma::vec& uprop, const arma::vec& y, const arma::mat& X, const arma::mat& Z);
RcppExport SEXP _JM2survClayton_logAcceptPoisson_n(SEXP betaSEXP, SEXP SigmaSEXP, SEXP ucurSEXP, SEXP upropSEXP, SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ucur(ucurSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type uprop(upropSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(logAcceptPoisson_n(beta, Sigma, ucur, uprop, y, X, Z));
    return rcpp_result_gen;
END_RCPP
}
// uSamplerPoissonCpp_n_acc
List uSamplerPoissonCpp_n_acc(const arma::vec& Xbeta, const arma::mat& Z, const arma::vec& u0, const arma::vec& y, const arma::mat& Sigma, int B, double sd0);
RcppExport SEXP _JM2survClayton_uSamplerPoissonCpp_n_acc(SEXP XbetaSEXP, SEXP ZSEXP, SEXP u0SEXP, SEXP ySEXP, SEXP SigmaSEXP, SEXP BSEXP, SEXP sd0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Xbeta(XbetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u0(u0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type sd0(sd0SEXP);
    rcpp_result_gen = Rcpp::wrap(uSamplerPoissonCpp_n_acc(Xbeta, Z, u0, y, Sigma, B, sd0));
    return rcpp_result_gen;
END_RCPP
}
// uSamplerPoissonCpp_n
arma::mat uSamplerPoissonCpp_n(const arma::vec& beta, const arma::mat& Sigma, const arma::vec& u0, const arma::vec& y, const arma::mat& X, const arma::mat& Z, int B, double sd0);
RcppExport SEXP _JM2survClayton_uSamplerPoissonCpp_n(SEXP betaSEXP, SEXP SigmaSEXP, SEXP u0SEXP, SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP BSEXP, SEXP sd0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u0(u0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type sd0(sd0SEXP);
    rcpp_result_gen = Rcpp::wrap(uSamplerPoissonCpp_n(beta, Sigma, u0, y, X, Z, B, sd0));
    return rcpp_result_gen;
END_RCPP
}
// ldmt
double ldmt(const arma::vec& x, double df, const arma::mat& Sigma);
RcppExport SEXP _JM2survClayton_ldmt(SEXP xSEXP, SEXP dfSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(ldmt(x, df, Sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_JM2survClayton_expWArma", (DL_FUNC) &_JM2survClayton_expWArma, 4},
    {"_JM2survClayton_gammaUpdate_fixDelta_general", (DL_FUNC) &_JM2survClayton_gammaUpdate_fixDelta_general, 13},
    {"_JM2survClayton_min0", (DL_FUNC) &_JM2survClayton_min0, 2},
    {"_JM2survClayton_loglikelihoodPoisson_preX", (DL_FUNC) &_JM2survClayton_loglikelihoodPoisson_preX, 5},
    {"_JM2survClayton_loglikelihoodPoissonCpp_n", (DL_FUNC) &_JM2survClayton_loglikelihoodPoissonCpp_n, 6},
    {"_JM2survClayton_logAcceptPoisson_n", (DL_FUNC) &_JM2survClayton_logAcceptPoisson_n, 7},
    {"_JM2survClayton_uSamplerPoissonCpp_n_acc", (DL_FUNC) &_JM2survClayton_uSamplerPoissonCpp_n_acc, 7},
    {"_JM2survClayton_uSamplerPoissonCpp_n", (DL_FUNC) &_JM2survClayton_uSamplerPoissonCpp_n, 8},
    {"_JM2survClayton_ldmt", (DL_FUNC) &_JM2survClayton_ldmt, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_JM2survClayton(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
