# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
expWArma <- function(iz_, b_, gam, h_) {
    .Call(`_JM2survClayton_expWArma`, iz_, b_, gam, h_)
}

gammaUpdate_fixDelta_general <- function(b_, z_, w_, pb_, haz, v_, u_, h_, K, q, qq, nev, jcount) {
    .Call(`_JM2survClayton_gammaUpdate_fixDelta_general`, b_, z_, w_, pb_, haz, v_, u_, h_, K, q, qq, nev, jcount)
}

min0 <- function(a, b) {
    .Call(`_JM2survClayton_min0`, a, b)
}

loglikelihoodPoisson_preX <- function(Xbeta, Z, u, y, Sigma) {
    .Call(`_JM2survClayton_loglikelihoodPoisson_preX`, Xbeta, Z, u, y, Sigma)
}

loglikelihoodPoissonCpp_n <- function(beta, Sigma, u, y, X, Z) {
    .Call(`_JM2survClayton_loglikelihoodPoissonCpp_n`, beta, Sigma, u, y, X, Z)
}

logAcceptPoisson_n <- function(beta, Sigma, ucur, uprop, y, X, Z) {
    .Call(`_JM2survClayton_logAcceptPoisson_n`, beta, Sigma, ucur, uprop, y, X, Z)
}

uSamplerPoissonCpp_n_acc <- function(Xbeta, Z, u0, y, Sigma, B, sd0) {
    .Call(`_JM2survClayton_uSamplerPoissonCpp_n_acc`, Xbeta, Z, u0, y, Sigma, B, sd0)
}

uSamplerPoissonCpp_n <- function(beta, Sigma, u0, y, X, Z, B, sd0) {
    .Call(`_JM2survClayton_uSamplerPoissonCpp_n`, beta, Sigma, u0, y, X, Z, B, sd0)
}

ldmt <- function(x, df, Sigma) {
    .Call(`_JM2survClayton_ldmt`, x, df, Sigma)
}

